upstream test_site_backend {
    server test-site:8000;
    keepalive 8;
}

# Routing from HTTP to HTTPS
# xn--h1agcefip8f.xn--p1ai is a punycode for ритмноль.рф
server {
    listen 80;
    server_name xn--h1agcefip8f.xn--p1ai ritmzero.ru;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name xn--h1agcefip8f.xn--p1ai ritmzero.ru;

    ssl_certificate     /etc/nginx/certs/test-site.crt;
    ssl_certificate_key /etc/nginx/certs/test-site.key;

    include /etc/nginx/conf.d/proxy.conf;
}
